// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace AdvertisingCampaign.Models
{
    public partial class AdvertisingCampaignContext : DbContext
    {
        public virtual DbSet<AdvertisingCampaign> AdvertisingCampaign { get; set; }
        public virtual DbSet<AdvertisingCampaignAudit> AdvertisingCampaignAudit { get; set; }

        public AdvertisingCampaignContext(DbContextOptions<AdvertisingCampaignContext> options) : base(options)
        {
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<AdvertisingCampaign>(entity =>
            {
                entity.Property(e => e.Created).HasDefaultValueSql("(getdate())");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}